### ISSUE TITLE
Create Installer

### ISSUE THREAD

**Issue by cryptiklemur** [symforium/symforium-core#6]

**Comment by jasonmccallister** [comment]
I think we should find a clever way to handle this, also focus on a version control system style deployment. Install but not actually require any local file modifications..

**Comment by cryptiklemur** [comment]
Curious, care to elaborate more?

**Comment by cryptiklemur** [comment]
I think this is mostly finished. Curious to see what else you wanted to elaborate on though @themccallister

**Comment by jasonmccallister** [comment]
Does the install require removal of files after installation?

**Comment by cryptiklemur** [comment]
Nope! :) The install changes the parameters located in `app/config/parameters.yml`, but thats it
